import type { Metadata } from "next";
import Navbar from "@/components/user-layout/Navbar";
import Container from "@/components/user-layout/Container";
import Footer from "@/components/user-layout/Footer";

export const metadata: Metadata = {
  title: "MicrodataStore",
  description: "Generated by create next app",
};

export default function PublicLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />
      <main className="flex-1">
        <Container>{children}</Container>
      </main>
      <Footer />
    </div>
  );
}